// new
export const FETCH_GITHUB_UESR_REQUESTED = 'FETCH_GITHUB_UESR_REQUESTED';
export const FETCH_GITHUB_USER__SUCCESSED = 'FETCH_GITHUB_USER__SUCCESSED';
export const FETCH_GITHUB_USER__FAILED = 'FETCH_GITHUB_USER__FAILED';

export const fetchUser = () => ({
  type: FETCH_GITHUB_UESR_REQUESTED,
  payload: {},
});
